### ISSUE TITLE
The partial code is now runnable, but there are still some minor issues.

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [AndresCasado/pergamo#13] opened 2024-04-10 15:25 UTC
Hello  @AndresCasado :
I'm sorry for bothering you again with another question.
After several days of debugging, the code can now run preliminarily. However, I'm a bit unclear about which files correspond to the train and test processes. If I want to train, what sequence of files should I execute? If I want to test, what sequence of files should I execute? My current understanding is that during training, I should first run run_recons.sh, then train_regressor.py. During testing, I should first run run_recons.sh, then run_regression.sh. I'm not sure if my understanding is correct.
When I run the file train_regressor.py, it throws the following error:
<img width="689" alt="3fd9c6bb8785d5dd781b9b3e48970e6" src="https://github.com/AndresCasado/pergamo/assets/165904272/753265ab-fb0a-4d05-9f8e-b60984ef36ef">
Does the dataset originally included in the project, as shown in the image, still needed?
<img width="180" alt="7a2c617388289bda0168efa634e8e0d" src="https://github.com/AndresCasado/pergamo/assets/165904272/3553ff32-d2d9-4e3e-8ac7-0b1822198821">
I'm eagerly awaiting your response. Thank you so much in advance.

**Comment by AndresCasado** [comment] 2024-04-11 08:53
Hello again!

The problem is it doesn't find the file named `0030_enc.pkl`. If I remember correctly, you need to encode the poses first, which can be done with `run_regression.sh`. If you open and edit the file, you can choose between using the AMASS dataset or our own dataset. Please uncomment the lines for our dataset and remove or comment out the lines for the AMASS dataset.

Let me know if this is enough!

**Comment by Liu-xiaoyu11** [comment] 2024-04-12 07:02
> Hello again!
> 
> The problem is it doesn't find the file named `0030_enc.pkl`. If I remember correctly, you need to encode the poses first, which can be done with `run_regression.sh`. If you open and edit the file, you can choose between using the AMASS dataset or our own dataset. Please uncomment the lines for our dataset and remove or comment out the lines for the AMASS dataset.
> 
> Let me know if this is enough!

Hey, @AndresCasado 
I'm sorry for the late response. Based on your guidance, I understand that the command in run_recons.sh is for reconstructing our dataset, and run_regression.sh is for building the regressor. If we want to use our own dataset, should the last command in run_regression.sh be changed to python3 predict_reconstructed_sequences.py? 
<img width="338" alt="61fcc9bded62b4220e4a79cf718406a" src="https://github.com/AndresCasado/pergamo/assets/165904272/d51e99b9-79a6-4cbc-8340-e28bb2d43f48">
I'm not entirely sure about this question yet. 
Also, I have questions about the testing process, as I'm not clear on which .py file corresponds to testing this regressor, and I haven't seen any division between test and train datasets in the dataset. Thank you very much for your patient guidance, and I look forward to your reply.

**Comment by AndresCasado** [comment] 2024-04-12 10:06
Hi!

`run_recons.sh` runs the reconstruction script on a given dataset. You will need to adapt your dataset so that it has the same structure as the one provided by us.

After you have reconstructed the dataset, you can train the regressor, using `train_regressor.py`. There is no Bash script provided for it. You may need to modify and adapt the Python code to use it, but that's the one you'll need to run in order to train it.

After that, you can run the prediction with `run_regression.sh`. Again, you may need to modify or adapt it. Please take a look inside the scripts used in it.

- `process_reconstructed_sequence.py` extracts the body poses and saves them in a new file
- `encode_reconstructed_poses.py` takes the body poses and encodes them into a 10-dimensional space
- `predict_reconstructed_sequences.py` (which should be the one used instead of `predict_amass_sequences.py`, I'll fix it now) runs the regression on the datasets

Sorry if it's not "plug and play". Let me know if you need more help.

**Comment by Liu-xiaoyu11** [comment] 2024-04-12 10:31
Hello, @AndresCasado 
You're very welcome! I'm glad I could help clarify things for you, and I'm happy to hear that you're gaining confidence in this field. 
Thank you very much, I basically understand now, and the code runs almost smoothly. 
**I just have one small question remaining: if I want to test the model that has been trained, do I need to use the AMASS dataset? I'm not sure about this question at the moment.** 
It's rare to see such patient responses like yours. I'm just starting out in this field, and your help has given me a lot of confidence. Once again, thank you very much.
I've been bothering you these days, I hope I haven't caused you any trouble.

**Comment by Liu-xiaoyu11** [comment] 2024-04-12 10:34
> Hello, @AndresCasado You're very welcome! I'm glad I could help clarify things for you, and I'm happy to hear that you're gaining confidence in this field. Thank you very much, I basically understand now, and the code runs almost smoothly. **I just have one small question remaining: if I want to test the model that has been trained, do I need to use the AMASS dataset? I'm not sure about this question at the moment.** It's rare to see such patient responses like yours. I'm just starting out in this field, and your help has given me a lot of confidence. Once again, thank you very much. I've been bothering you these days, I hope I haven't caused you any trouble.

If I need the AMASS dataset, which specific version should I download?

**Comment by Liu-xiaoyu11** [comment] 2024-04-13 13:35
Hello， @AndresCasado 
The .pc2 format data in the project requires a specific plugin or configuration for 3ds Max, right?

**Comment by AndresCasado** [comment] 2024-04-15 15:17
Hello again!

Sorry for the late response.

I'll check the AMASS dataset when I get the chance and try to tell you what you need.

About the .pc2 file, I use it with Blender. To use it you need to import a .obj file and then add a Mesh Cache modifier, change the format to PC2 and then select the file. I can't tell you anything about 3ds Max as I've never used it.

**Comment by Liu-xiaoyu11** [comment] 2024-04-16 02:41
Hi, @AndresCasado :
It would be my great honor to respond. I just downloaded Blender and followed the steps you guided me through. The clothes are moving, but the 'character' isn't visible; only the clothes are moving. I'm not sure what went wrong. In the end, I found there are two .pc2 files. Do both of these files have to be used, or is one of them enough? 
<img width="144" alt="294809f6cae17995304e566fdaaad9a" src="https://github.com/AndresCasado/pergamo/assets/165904272/d1c4a099-d4ac-4b1f-9c02-a57e39fcd6dd">
My understanding is that _body.pc2 should be the animation for the character, but I'm not sure if I'm interpreting this correctly.
https://github.com/AndresCasado/pergamo/assets/165904272/4b7ec778-0a2a-45f2-b791-ae7df4d2b423
Thank you very much for your patient guidance, and I look forward to your reply.

**Comment by Liu-xiaoyu11** [comment] 2024-04-16 02:51
Currently, I still have a question. I downloaded the dataset DatosDan and then ran run_recons.sh which should correspond to the part of reconstructing the dataset in the article. However, there is no .pkl file in the reconstructed data, which means the subsequent step of run_regression.sh cannot be executed. So, what is the purpose of this dataset DatosDan? Currently, I'm using the dataset train_sequence and validation_sequence provided in the project。

**Comment by Liu-xiaoyu11** [comment] 2024-04-16 02:55
Hello， @AndresCasado 
Currently, I still have a question. I downloaded the dataset DatosDan and then ran run_recons.sh which should correspond to the part of reconstructing the dataset in the article.
<img width="205" alt="88994e6af271bcd2f2f183421cd37fa" src="https://github.com/AndresCasado/pergamo/assets/165904272/48d91ce6-e7e1-4498-b03e-b4913f42068e">
 However, there is no .pkl file in the reconstructed data, which means the subsequent step of run_regression.sh cannot be executed. So, what is the purpose of this dataset DatosDan?
<img width="212" alt="ea3bc74aa7f4fd68ecdf6e45856200d" src="https://github.com/AndresCasado/pergamo/assets/165904272/5729ebc4-7497-491d-a58e-54addf792772">
 Currently, I'm using the dataset train_sequence and validation_sequence provided in the project。
<img width="161" alt="9e4e5e98a4caac1cbe317ca4bd2bd74" src="https://github.com/AndresCasado/pergamo/assets/165904272/2b65b139-c4d2-4d04-858f-841316c9081a">

**Comment by Liu-xiaoyu11** [comment] 2024-04-16 02:59
The regressor has out_channels=4424. Is there any special meaning to this? I couldn't find an answer in the article.
<img width="422" alt="微信图片_20240416105834" src="https://github.com/AndresCasado/pergamo/assets/165904272/2daa366c-c909-4670-a32e-8b8674697169">

**Comment by AndresCasado** [comment] 2024-04-16 07:37
> Hi, @AndresCasado : It would be my great honor to respond. I just downloaded Blender and followed the steps you guided me through. The clothes are moving, but the 'character' isn't visible; only the clothes are moving. I'm not sure what went wrong. In the end, I found there are two .pc2 files. Do both of these files have to be used, or is one of them enough? <img alt="294809f6cae17995304e566fdaaad9a" width="144" src="https://private-user-images.githubusercontent.com/165904272/322682936-d1c4a099-d4ac-4b1f-9c02-a57e39fcd6dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg5MzAsIm5iZiI6MTcxMzI0ODYzMCwicGF0aCI6Ii8xNjU5MDQyNzIvMzIyNjgyOTM2LWQxYzRhMDk5LWQ0YWMtNGIxZi05YzAyLWE1N2UzOWZjZDZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjExNDI1YjM2NDg1ZGU2MGFkZGY3OTg0OTkwMDQ0ZDhhZjdlYTA2M2Y3MGU1YmEwYzZhOTExYTY4NWI4N2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0fehHWBJ44R4-O3Fn5NujMX2WNTWvaA9VnXpsUMFCj0"> My understanding is that _body.pc2 should be the animation for the character, but I'm not sure if I'm interpreting this correctly. https://github.com/AndresCasado/pergamo/assets/165904272/4b7ec778-0a2a-45f2-b791-ae7df4d2b423 Thank you very much for your patient guidance, and I look forward to your reply.

I no longer have the development environment installed, so I cannot generate the files right now. Please, try to use the `*_body.pc2` file with a SMPL-X mesh.



> Hello， @AndresCasado Currently, I still have a question. I downloaded the dataset DatosDan and then ran run_recons.sh which should correspond to the part of reconstructing the dataset in the article. <img alt="88994e6af271bcd2f2f183421cd37fa" width="205" src="https://private-user-images.githubusercontent.com/165904272/322685709-48d91ce6-e7e1-4498-b03e-b4913f42068e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg5MzAsIm5iZiI6MTcxMzI0ODYzMCwicGF0aCI6Ii8xNjU5MDQyNzIvMzIyNjg1NzA5LTQ4ZDkxY2U2LWU3ZTEtNDQ5OC1iMDNlLWI0OTEzZjQyMDY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjFhNTA0OGI0NThkYmQ0ZDllYjY2Yzk1NTZkMTkwM2Y2ZDhlMDQ1Y2VkYTdhZDQ3YTU4ZjU4YWFlMmI2MTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rVxzT8e4CIR0ZvgwGtM134VSiW8SoRQF5WrsQue82XU"> However, there is no .pkl file in the reconstructed data, which means the subsequent step of run_regression.sh cannot be executed. So, what is the purpose of this dataset DatosDan? <img alt="ea3bc74aa7f4fd68ecdf6e45856200d" width="212" src="https://private-user-images.githubusercontent.com/165904272/322685759-5729ebc4-7497-491d-a58e-54addf792772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg5MzAsIm5iZiI6MTcxMzI0ODYzMCwicGF0aCI6Ii8xNjU5MDQyNzIvMzIyNjg1NzU5LTU3MjllYmM0LTc0OTctNDkxZC1hNThlLTU0YWRkZjc5Mjc3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDBlN2ZmNTE0NjA4MDczOGZmYzA4NjA1NzgzY2ZkOGU2NThhZDM5ZTk4ZmQ0MTRhMDk0MDZmYTk0YTZhMDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8QdB0_1AILgj5dvLLZkZ-xDsQuOH7-B7H1_SUspqNMQ"> Currently, I'm using the dataset train_sequence and validation_sequence provided in the project。 <img alt="9e4e5e98a4caac1cbe317ca4bd2bd74" width="161" src="https://private-user-images.githubusercontent.com/165904272/322685647-2b65b139-c4d2-4d04-858f-841316c9081a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg5MzAsIm5iZiI6MTcxMzI0ODYzMCwicGF0aCI6Ii8xNjU5MDQyNzIvMzIyNjg1NjQ3LTJiNjViMTM5LWM0ZDItNGQwNC04NThmLTg0MTMxNmM5MDgxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzEyMjExNjFhODU5M2VmMTcxMjU5MTIzYjdkNDFkMGRlMWY1MDFlNWZjNjQ2OWZlNjExYTQ5ZGQ2NGVlM2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wm973hXlIkGDPO7n9bkQ5HQFeFuaBEKi5LHimN_w6ZU">

I can see the `.pkl` files in `data/train_sequence/poses`. Please, provide the error message so that I can better understand the problem.



> The regressor has out_channels=4424. Is there any special meaning to this? I couldn't find an answer in the article. <img alt="微信图片_20240416105834" width="422" src="https://private-user-images.githubusercontent.com/165904272/322686561-2daa366c-c909-4670-a32e-8b8674697169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDg5MzAsIm5iZiI6MTcxMzI0ODYzMCwicGF0aCI6Ii8xNjU5MDQyNzIvMzIyNjg2NTYxLTJkYWEzNjZjLWM5MDktNDY3MC1hMzJlLThiODY3NDY5NzE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNjIzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWRhNGY1MzE1MWE3N2Q3ZGI2NjA5MjY2NDExZDFhZTFiMjM3MTcxZTk0YzIzNDg0NmQyOWQ0MTI3MTFiYjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gQkhNplr0Crr3K35x8yveDsR2-2jw-ydFFxVEwwPmPY">

It's the number of vertices of the garment template. You can find a reference (which I admit is a bit hard to find) just above paragraph 6 in the paper. https://github.com/AndresCasado/pergamo/blob/bfa1b4c0c85dcc3d8e6c2f9f4153c86b9581c3bb/regressor.py#L23-L24 Here you can see the size is actually multiplied by 3 for the 3 spatial dimensions.

---

I'm closing the issue as it is diverging from the original problem. From now on, please, open a different issue for each individual problem or question. I'll be glad to help.

**Closed as completed by AndresCasado** 2024-04-16 07:37 UTC
